name: CI Pipeline

on:
  push:
    tags:
      - 'rc-*'

defaults:
 run:
  working-directory: ./backend

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Setup Node.js environment
      uses: actions/setup-node@v4.0.3
      with:
        node-version: '21.x'

    - name: Install dependencies
      run: npm ci

    - name: Run static code analysis
      run: npm run lint

    - name: Run unit tests
      run: npm run test

    - name: Build the project
      run: npm run build --if-present

    - name: Create release package
      run: |
        TAG_NAME=$(echo $GITHUB_REF | sed 's/refs\/tags\///')
        ZIP_NAME="${TAG_NAME}.zip"
        # Create the zip file excluding the node_modules folder
        zip -r $ZIP_NAME . -x "node_modules/*"
        mkdir -p release
        mv $ZIP_NAME release/

    - name: Upload release package
      uses: actions/upload-artifact@v3
      with:
        name: release-package
        path: release/
